import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import meRouter from "./me";
import employeesRouter from "./employees";
import attendanceRouter from "./attendance";
import leaveRouter from "./leave";
import onboardingRouter from "./onboarding";
import assetsRouter from "./assets";
import kraRouter from "./kra";
import reportsRouter from "./reports";
import adminRouter from "./admin";
import automationsRouter from "./automations";
import selfServiceRouter from "./selfservice";
import importsRouter from "./imports";
import reimbursementsRouter from "./reimbursements";
import investmentsRouter from "./investments";
import lettersRouter from "./letters";
import zktecoPingRouter from "./zkteco";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(meRouter);
router.use(employeesRouter);
router.use(attendanceRouter);
router.use(leaveRouter);
router.use(onboardingRouter);
router.use(assetsRouter);
router.use(kraRouter);
router.use(reportsRouter);
router.use(adminRouter);
router.use(automationsRouter);
router.use(selfServiceRouter);
router.use(importsRouter);
router.use(reimbursementsRouter);
router.use(investmentsRouter);
router.use(lettersRouter);
router.use(zktecoPingRouter);

export default router;
